### ISSUE TITLE
Wrap `openssl_x509` resource for self-signed cert creation

### ISSUE THREAD

**Issue by patcon** [schubergphilis/letsencrypt#1]
So glad this cookbook exists! I'll be testing it out and submit PRs for things I might need :)

Not sure if I need this yet, but noticed that you were generating self-signed keys yourself, and thought you might be interested in using the `openssl` library cookbook for DRYness. Seems that you'd need to push at least one change upstream (re: extensions), but it should be doable.

https://github.com/chef-cookbooks/openssl#openssl_x509

**Comment by thoutenbos** [comment]
Thanks for your feedback!

I noticed the acme-client rubygem also added certificate helpers, so that might be interesting as well as it will be one less dependency for the cookbook.

**Comment by thoutenbos** [comment]
Now using the wrapper from Acme::Client::CertificateRequest
