### ISSUE TITLE
"undefined method `validation' for Chef::Resource::RubyBlock" error

### ISSUE THREAD

**Issue by troyready** [schubergphilis/letsencrypt#10]
After attempting to use the new alt_names functionality, my certification creations are failing at the [certificate provider's line 23](https://github.com/schubergphilis/letsencrypt/blob/master/providers/certificate.rb#L123) -- I think `all_validations` should be referenced instead?

**Comment by tibra** [comment]
I was having this problem while there were still nginx redirects from http to https active which prevented the acme-challenge to be retrievable via http for the requested domain.

**Comment by thoutenbos** [comment]
It probably means that at least one of the validations failed. Better reporting should be added here (which domains succeeded and which one failed).

Is your tokenpath reachable from all alt_names ?

**Comment by vigosan** [comment]
Same error `NoMethodError: undefined method `validation' for Chef::Resource::RubyBlock`

**Comment by troyready** [comment]
@vigosan the fix for this is in the master branch -- it'll be included in the next cookbook release. For now, you can use it by directly updated your berksfile to pull from github (or whatever equivalent method of getting cookbooks you use).

also, fwiw in case it isn't clear, this code is only evaluated because let's encrypt was not able to correctly generate a cert for you. I ran into this before when I added a SAN to my resource without changing the key. Just thought i should mention that another way to avoid the error is to fix whatever underlying issue is preventing your cert from being generated.

**Comment by vigosan** [comment]
It works! thanks a lot.

**Comment by thoutenbos** [comment]
Also released in v0.1.4 now!
