### ISSUE TITLE
Recommended workflow for certificate renewal

### ISSUE THREAD

**Issue by tibra** [schubergphilis/letsencrypt#12]
Hi Thijs,

thanks for your great work with this cookbook. Since renewal should be automated, what would be your recommended workflow? 
I'm using chef-solo, so I could run chef-solo once a month in a cron job. However, since there is a lot going on during a chef run I'd be more comfortable only running a single script. Would you recommend this or does anything come to mind that goes against this?

Thank you!

Tim

**Comment by thoutenbos** [comment]
Hi Tim,

I guess it depends on your specific setup. If you use chef only for certificates then maybe the official Let's Encrypt client is better suited for it. If you use chef to bootstrap all sorts of resources on your server then only running it once a month could introduce a risk of it destructing other components while renewing the certificate. Maybe only run this cookbook in the cronjob entry?

Best,
Thijs

**Comment by tibra** [comment]
Hey Thijs,

good idea, I'm creating cronjobs inside my letsencrypt recipe to run once a week:
```
# Chef Name: ssl_renewal_via_chef
0 5 * * 1 /usr/local/bin/chef-solo -j /etc/chef/node.json -o "recipe[letsencrypt],recipe[nginx]"
```

Thanks :-)

**Comment by cromulus** [comment]
Could we perhaps put this on the readme?

Thanks! Great work!

**Comment by cbou** [comment]
Does this still work?
