### ISSUE TITLE
No registration exists matching provided key

### ISSUE THREAD

**Issue by johnnymeronny** [schubergphilis/letsencrypt#24]
Hi there,

I am trying to get your acme_client code to run. It works with the staging server, but when I try to use the real endpoint I get the error:

    Acme::Client::Error::Unauthorized
    ---------------------------------
    No registration exists matching provided key

My code is pretty much the same as yours, this are my attributes:

default['letsencrypt']['contact'] = 'mailto:myrealaddress@mail.com'
default['letsencrypt']['endpoint'] = 'https://acme-v01.api.letsencrypt.org'

I am running Ubuntu 14.04. Do you have any idea why this could happen?

Thanks!

**Comment by thoutenbos** [comment]
Sounds like you registered on the staging server, and are now using your staging key to authenticate to the real endpoint. Try to clear your `node['letsencrypt']['private_key']` and try again.

**Comment by johnnymeronny** [comment]
Thanks, that was it. I deleted it with `knife exec -E 'nodes.transform(:all) { |n| n.normal_attrs.delete("letsencrypt"); n.save() }'`. Do you think that is a good way to solve this or is there a better way if I run into this problem again in the future?

**Comment by thoutenbos** [comment]
Sure, looks fine, as long as it clears the attribute. I would probably have used `knife node edit` instead but this looks like it could also work :)

**Comment by johnnymeronny** [comment]
Alright, good to know. Thanks and good evening.
