### ISSUE TITLE
Intermediate certificates

### ISSUE THREAD

**Issue by chr4** [schubergphilis/letsencrypt#28]
Does this client library support full certificate chains?
The certificates I get are missing the [intermediate certificates](https://letsencrypt.org/certificates/) of letsencrypt, therefore not being trusted on many clients. 

Is there an option I didn't find, or is this an issue? Unfortunately, as there's X1 X2 X3 X4, it's not as simple as simply appending the certificate chain to the generated certificate.

Did I miss something?

**Comment by thoutenbos** [comment]
Did you check the `chain` and `fullchain` options for the provider? Those should be able to provide you with the correct intermediate certificate.

**Comment by chr4** [comment]
That's exactly what I was looking for. Sorry, missed it in the docs.
Thanks, forks perfectly!
