### ISSUE TITLE
Error use recipe letsencript

### ISSUE THREAD

**Issue by AnselmoPfeifer** [schubergphilis/letsencrypt#32]
I used your recipe and return error bellow:

================================================================================[0m
[31mRecipe Compile Error in /var/chef/cookbooks/empresa/recipes/letsencript.rb[0m
================================================================================[0m
[0mNoMethodError[0m
-------------[0m
undefined method `compile_time' for Chef::Resource::ChefGem[0m
[0mCookbook Trace:[0m ---------------[0m
  /var/chef/cookbooks/letsencrypt/recipes/default.rb:24:in `block in from_file'
[0m  /var/chef/cookbooks/letsencrypt/recipes/default.rb:21:in `from_file'
[0m  /var/chef/cookbooks/empresa/recipes/letsencript.rb:2:in `from_file'[0m

[0mRelevant File Content:[0m ----------------------[0m
/var/chef/cookbooks/letsencrypt/recipes/default.rb:
[0m
[0m 17:  # See the License for the specific language governing permissions and
[0m 18:  # limitations under the License.
[0m 19:  #
[0m 20:  
[0m 21:  chef_gem 'acme-client' do
[0m 22:    action :install
[0m 23:    version '0.2.2'
[0m 24>>   compile_time true
[0m 25:  end
[0m 26:  
[0m 27:  require 'acme-client'
[0m 28:  [0m

[0m[2016-06-06T14:45:53-03:00] ERROR: Running exception handlers
[2016-06-06T14:45:53-03:00] ERROR: Exception handlers complete
[2016-06-06T14:45:53-03:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2016-06-06T14:45:53-03:00] ERROR: undefined method `compile_time' for Chef::Resource::ChefGem
[2016-06-06T14:45:53-03:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Build step 'Execute shell' marked build as failure
Notifying upstream projects of job completion
Finished: FAILURE

--
Ambient description:
System: ubuntu 14.04 
Ruby versions tested: 1.9, 2.1 and 2.2
I installed this gem manually with 'gem install acme-client -v 0.2.4' continue the error.

**Comment by thoutenbos** [comment]
What version of chef-client are using?

**Comment by AnselmoPfeifer** [comment]
chef-client -v
Chef: 11.16.4

**Comment by AnselmoPfeifer** [comment]
Thoutenbos 
Area you to publish the new version in chef super market?

https://supermarket.chef.io/cookbooks/letsencrypt

**Comment by thoutenbos** [comment]
Yep, will be a new release tomorrow or the day after

**Comment by AnselmoPfeifer** [comment]
Thank you very much
