### ISSUE TITLE
uninitialized constant Acme

### ISSUE THREAD

**Issue by zeknox** [schubergphilis/letsencrypt#37]
Added the following to Berksfile
<pre>cookbook 'letsencrypt', '~> 1.0.0'</pre>

Added the following to metadata.rb
<pre>depends 'letsencrypt'</pre>

Created a recipe similar to the following:
<pre>
letsencrypt_certificate 'test.example.com' do
  crt      '/etc/ssl/test.example.com.crt'
  key      '/etc/ssl/test.example.com.key'
  method   'http'
  wwwroot  '/var/www'
end
</pre>

When running a converge on this node it's throwing the error below. Any insight would be appreciated

<pre>
           NameError
           ---------
           uninitialized constant Acme
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/letsencrypt/libraries/acme.rb:37:in `acme_client'
           /tmp/kitchen/cache/cookbooks/letsencrypt/libraries/acme.rb:49:in `acme_authz'
           /tmp/kitchen/cache/cookbooks/letsencrypt/providers/certificate.rb:54:in `block (2 levels) in class_from_file'
           /tmp/kitchen/cache/cookbooks/letsencrypt/providers/certificate.rb:53:in `map'
           /tmp/kitchen/cache/cookbooks/letsencrypt/providers/certificate.rb:53:in `block in class_from_file'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
</pre>

**Comment by funzoneq** [comment]
You need to include_recipe 'letsencrypt' in your cookbook to get the gem installed.

**Comment by zeknox** [comment]
Thanks boss, this has addressed this particular issue.  However, I'm not running into a different issue while converging. While trying to install the acme-client it's throwing an error saying I'm running the wrong version of ruby, however my ruby version appears to be the latest stable version.

<pre>
         STDOUT: 
         STDERR: ERROR:  Error installing acme-client:
         	activesupport requires Ruby version >= 2.2.2.
         ---- End output of /opt/ch
</pre>

However, the version of ruby installed on this node is 2.3.1.  See output below:
<pre>
# ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
</pre>

Any insight here would be appreciated!

**Comment by thoutenbos** [comment]
Just released a new version of the cookbook which should fix this. There's some problems with dependencies on the ruby gem.

**Comment by zeknox** [comment]
Thank you folks so much for the quick responses. This is top notch support and much appreciated.  This appears to have addressed my issue.  Now I'm onto my next issue which I don't believe is an issue on your part:
<pre>
Validation failed for domain
</pre>

**Comment by zeknox** [comment]
Thank you again for the assistance, I now have valid letsencrypt SSL certs using this cookbook, very powerful stuff!
