### ISSUE TITLE
Ruby version block

### ISSUE THREAD

**Issue by jopelope** [schubergphilis/letsencrypt#38]
Hello. Since today I have problems using this cookbook because of the ACME client.

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    chef_gem[acme-client] (letsencrypt::default line 21) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/chef/embedded/bin/gem install acme-client -q --no-rdoc --no-ri -v "0.2.4" ----
    STDOUT: 
    STDERR: ERROR:    Error installing acme-client:
      activesupport requires Ruby version >= 2.2.2.
    ---- End output of /opt/chef/embedded/bin/gem install acme-client -q --no-rdoc --no-ri -v "0.2.4" ----
    Ran /opt/chef/embedded/bin/gem install acme-client -q --no-rdoc --no-ri -v "0.2.4" returned 1`

Chef is using this Ruby version (Ubuntu 14.04):

    /opt/chef/embedded/bin/ruby -v
    ruby 2.1.8p440 (2015-12-16 revision 53160) [x86_64-linux]

Do you know any way how to resolve this? This is a really, really big problem for me :(

Thanks!

**Comment by thoutenbos** [comment]
Hello,

It's stated in the error:
activesupport requires Ruby version >= 2.2.2.

Guess it's time to upgrade chef / ruby ?

Best,
THijs

**Comment by jopelope** [comment]
Well, I know that this is caused by the Ruby version (thus the title of the issue), but I haven't found a way to upgrade the Chef / embedded Ruby version on the node. It is a fresh install, so I would think that the latest version is used.

**Comment by thoutenbos** [comment]
Maybe there's a newer chef-client version ?

**Comment by jopelope** [comment]
Sadly there is not, as I said I am running the latest chef-client version. 12.12.13 that is.

**Comment by thoutenbos** [comment]
Looks like it's caused by a recent commit in acme-client

https://github.com/unixcharles/acme-client/commit/0e54673de0ab81d5989420671f386f355c059eaa

**Comment by thoutenbos** [comment]
Can you try with `acme-client` 0.3.6 ?

**Comment by jopelope** [comment]
Same problem with 0.3.6. Shouldn't it be greater-equal instead of less-equal in that patch anyway? Maybe I should open an issue at acme-client.

**Comment by thoutenbos** [comment]
Nice, let's hope it's fixable there. In the mean time I am preparing v1.0.1 with pinned version on `activesupport` and `json-jwt` to get things working again.

**Comment by thoutenbos** [comment]
https://github.com/schubergphilis/letsencrypt/tree/v1.0.1
