### ISSUE TITLE
Compile / Converge issues

### ISSUE THREAD

**Issue by vegardx** [schubergphilis/letsencrypt#6]
It seems like there are some problems with generating the private key and requesting a new certificate, as the key is not generated and available in the same phase. I'm sure there are lots of ways to fix this, one of them being generating self-signed key for the same domain first.

**Comment by thoutenbos** [comment]
Good point. I mostly use the `selfsigned` provider before requesting the real certificate so I didn't find this issue yet.

Will release version 0.1.2 with the fix included :+1:
