### ISSUE TITLE
Recommended approach for apache

### ISSUE THREAD

**Issue by patcon** [schubergphilis/letsencrypt#9]
Not sure whether this is too opinionated, but as someone who just worked through how to get this working with apache, I thought perhaps it might be useful to bring some bits into this cookbook:

https://github.com/parallels-cookbooks/confluence/pull/93/files

Any thoughts? Mostly thinking the "letencrypt.conf" apache config fragment approach. Seems like it might be nice to add and create a test for, so that the current test goes a little bit further in explaining how to get things working

(I'm aware that some apps [might get confused by being proxied](https://github.com/letsencrypt/letsencrypt/issues/2164#issuecomment-172710091), but seems to be working fine in our situation)

**Comment by thoutenbos** [comment]
I guess there are so many use cases that this cookbook should focus primarily on requesting the certificate, leave serving the token files to the implementer of the specific scenario. With that, it is ofcourse very helpful to include examples for some often used setup's, like apache.

If you feel some helpers could be re-used by a wide range of apache users, maybe you can add them as a different recipe? As long as it's not forced to all users it should be fine.
